spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  # 쿼리 파라미터의 값을 로그로 남김
#  org.hibernate.type: trace

cloud:
  aws:
    credentials:
      profileName: hazel
      session:
        durationMinute:
          raonk: 15
    s3:
      imgBucket: nullnull-motivation
      rootDirectory: images/
      temp:
        session:
          role:
            arn: arn:aws:iam::188209031864:user/hazel
            sessionName: ets-dev-s3-role